### PR TITLE
Relicense fully to Apache-2.0 WITH LLVM-exception.

### LINKED ISSUE #7: Relicense fully under Apache-2.0 WITH LLVM-exception
Currently, regalloc2 contains some MPL code. This code was a result of an initial translation effort that started from IonMonkey's register allocator; IonMonkey (as part of SpiderMonkey and thus the Firefox codebase) is licensed under the MPL. This is a perfectly fine open-source license, but ideally, we would like to relicense this code to fall under `Apache-2.0 WITH LLVM-exception`, in alignment with other BA codebases, if all of the relevant parties agree and are happy with this.

cc @tschneidereit, who has been in contact with various folks about this and is working hard to obtain the appropriate signoffs (thanks!).

### PR DESCRIPTION
**Pull request by cfallin**
Large parts of the code in regalloc2 are currently licensed under the Mozilla Public License (MPL) 2.0, because they derive in meaningful ways from the register allocator in IonMonkey, which is part of Firefox. The relevant source files are marked as such, with references to the files in the Firefox source tree.

The intent of the regalloc2 project was to port the register allocator from Firefox to use in Cranelift, borrowing good technology and improving on it in the spirit of open source.

However, Several use-cases of Cranelift require, or at least strongly prefer, the Apache-2.0 license with the LLVM exception (matching the license of Cranelift itself, and Bytecode Alliance projects generally). While using this license is not strictly necessary for
regalloc2 to be usable (The MPL is an excellent open-source license!), relicensing fully under this license to harmonize with the rest of Cranelift and Bytecode Alliance codebases significantly widens possibilities and reduces friction; then regalloc2 is "just another part of Cranelift" and doesn't have to be treated specially.

The source in `src/ion/` specifically began as a fairly direct port of the algorithms in the following files in the `mozilla-central` repository (Firefox codebase):

* The bulk of the "backtracking allocator" algorithm:
  * `js/src/jit/BacktrackingAllocator.{cpp,h}`
* Helpers and definitions in the surrounding infrastructure:
  * `js/src/jit/RegisterAllocator.h`
  * `js/src/jit/RegisterAllocator.cpp`
  * `js/src/jit/StackSlotAllocator.h`
  * `js/src/jit/LIR.h`
* A few data structure implementations:
  * `js/src/ds/SplayTree.h`
  * `js/src/ds/PriorityQueue.h`

Subsequent work in improving regalloc2 has caused it to drift from the direct port -- for example, it no longer uses splay trees or the direct port of the priority queue above -- but it is of course very clearly still a derivative work.

Analysis of the contributors to these files indicates that we need signoff from the following folks:

* Mozilla Corp, for contributions made by Mozilla employees (the majority of the code). Communications with Mozilla (thanks @tschneidereit and @bholley for doing the work here!) indicate that @ekr is able to sign off when ready here.

* Andy Wingo, specifically for the work done in [Bug 1620197](https://bugzilla.mozilla.org/show_bug.cgi?id=1620197) and [Bug 1609057](https://bugzilla.mozilla.org/show_bug.cgi?id=1609057) to generalize the stack allocator for a Wasm feature (multiple returns).

Additionally, since the initial port, we have had three contributions from @Amanieu: [#9](https://github.com/bytecodealliance/regalloc2/pull/9), [#11](https://github.com/bytecodealliance/regalloc2/pull/11), [#13](https://github.com/bytecodealliance/regalloc2/pull/13).

So, if everyone applicable is happy with this relicensing, this PR removes the MPL-2.0 license in `src/ion/` and marks all files as covered under `Apache-2.0 WITH LLVM-exception`. Please let us know if this is OK!

Signoffs:

- [x] @ekr, for Mozilla's contributions
- [x] @wingo, for contributions to original code in `mozilla-central`
- [x] @Amanieu, for the three PRs linked above

Thanks!

(Fixes #7)

### CODE REVIEW

**Comment by Amanieu** [comment]
OK for me!

**Comment by wingo** [comment]
ok for me!

**Comment by ekr** [comment]
Approved by me.

**Comment by cfallin** [comment]
Thanks all! With all signoffs in, consider the code relicensed; merging now!

**Comment by bjorn3** [comment]
🎉

**Pull request merged**
